services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_app
    restart: unless-stopped
    working_dir: /var/www
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000" # Porta para a API REST
    volumes:
      - .:/var/www
    networks:
      - mini_crm
    depends_on: # ADICIONE ESTAS 3 LINHAS
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: crm_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crm_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mini_crm

  redis:
    image: redis:alpine
    container_name: crm_redis
    restart: unless-stopped
    networks:
      - mini_crm
  queue:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: crm_queue
      restart: unless-stopped
      working_dir: /var/www
      command: ["php", "artisan", "queue:work", "--tries=3"]
      volumes:
        - .:/var/www
      networks:
        - mini_crm
      depends_on:
        - db
        - redis

  reverb:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: crm_reverb
      restart: unless-stopped
      working_dir: /var/www
      command: ["php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8080"]
      ports:
        - "8080:8080" # A porta do WebSocket agora vive aqui
      volumes:
        - .:/var/www
      networks:
        - mini_crm
      depends_on:
        - redis

networks:
  mini_crm:
    driver: bridge

volumes:
  db_data: